config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments
  validates :name, :email, :password, :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
     @comment = Comment.create(reply: comment_params[:reply], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:reply, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id:current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
      tweet = Tweet.find(params[:id])
      if tweet.user_id == current_user.id
        tweet.update(tweet_params)
      end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    @name = @tweet.user.name

  end



  private
  def tweet_params
    params.require(:tweet).permit(:image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @tweets = current_user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script   src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  <nav class="#6d4c41 brown darken-1">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">京都良いとこ</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><a href="/users/<%= current_user.id %>">マイページ</a></li>
        <li><%= link_to "投稿する", new_tweet_path, method: :get %></li>

       <% else %>
       <li><%= link_to "ログイン", new_user_session_path, method: :get %></li>
        <li><%= link_to "新規登録", new_user_registration_path, method: :get %></li>
       <% end %>
      </ul>
    </div>
  </nav>

<div class="container">
<script type="text/javascript" src="./app.js"></script>
    <%= yield %>

</div>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="row">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-image">
              <img src= <%= tweet.image %>>
              <span class="card-title">
              <%= tweet.user.name %>
              </span>
              <%= link_to "/tweets/#{tweet.id}", class: "btn-floating halfway-fab waves-effect waves-light #ffb300 amber darken-1", method: :get do %>
              <i class="material-icons">chat_bubble_outline
              </i>
              <% end %>

            </div>
            <div class="card-content">
              <p><%= tweet.text %></p>
            </div>
            <% if user_signed_in? && current_user.id == tweet.user_id %>
            <div class="card-action ">
              <%= link_to "編集", "/tweets/#{tweet.id}/edit", method: :get %>
              <%= link_to "削除", "/tweets/#{tweet.id}", method: :delete %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/tweets/create.html.erb
<div class="row">
        <div class="col s12 m6">
          <div class="card #fff3e0 orange lighten-5">
            <div class="card-content black-text">
              <p>投稿しました</p>
            </div>
            <div class="card-action">
              <a href="/">投稿一覧へ戻る</a>
            </div>
          </div>
        </div>
      </div>

app/views/tweets/destroy.html.erb
<div class="row">
        <div class="col s12 m6">
          <div class="card #fff3e0 orange lighten-5">
            <div class="card-content black-text">
              <p>削除が完了しました</p>
            </div>
            <div class="card-action">
              <a href="/">投稿一覧へ戻る</a>
            </div>
          </div>
        </div>
      </div>

app/views/tweets/edit.html.erb
<div class="row">
 <%= form_for @tweet, html: { class: "col s12"} do |f|%>
        <div class="row">
          <div class="input-field col s6">
            <%= f.text_field :image, id: "input_text", value: @tweet.image %>

          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :text, id: "textarea1", class:"materialize-textarea", value: @tweet.text %>

          </div>
        </div>
        <%= button_tag :action, type: "submit", class: "btn #6d4c41 brown darken-1" do%>更新
        <i class="material-icons right">send</i>
        <% end %>
<% end %>
 </div>

app/views/tweets/index.html.erb
<div class="contents row">
<% @tweets.each do |tweet| %>
<%= render partial: "tweet", locals: {tweet: tweet} %>

<% end %>

<%= paginate(@tweets) %>

</div>

app/views/tweets/new.html.erb
<div class="row">
 <%= form_for @tweet, html: {class: "col s12"} do |f| %>
        <div class="row">
          <div class="input-field col s6">
            <%= f.text_field :image, id: "input_text", placeholder: "画像URL" %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :text, id: "textarea1", html: {class: "materialize-textarea"}, placeholder: "テキスト" %>

          </div>
        </div>
        <%= button_tag :action, type: "submit", class: "btn #6d4c41 brown darken-1" do%>投稿
        <i class="material-icons right">send</i>
        <% end %>
<% end %>
</div>

app/views/tweets/show.html.erb
<p><%= @name %>さんの投稿</p>

<div class="row">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-image">
              <img src= <%= @tweet.image %>>
              <span class="card-title">
                <%= @tweet.user.name %>
              </span>
            </div>
            <div class="card-content">
              <p><%= @tweet.text %></p>
            </div>
            <% if user_signed_in? && current_user.id == @tweet.user_id %>
            <div class="card-action">
              <%= link_to "編集", "/tweets/#{@tweet.id}/edit", method: :get %>
              <%= link_to "削除", "/tweets/#{@tweet.id}", method: :delete %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
</div>

<div class="row">
    <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post, class: "col s12") do %>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">chat_bubble_outline</i>
          <textarea id="icon_prefix2" class="materialize-textarea" name="reply"></textarea>
      </div>
  </div>
<button class="btn #6d4c41 brown darken-1" type="submit" name="action">コメント
    <i class="material-icons right">send</i>
  </button>
  <% end %>

<% if @comments %>
 <% @comments.each do |comment| %>
<div class="row">
    <div class="col s12 m5">
      <div class="card-panel white">
        <span class="black-text">
          <storng><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.reply %>
        </span>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/tweets/update.html.erb
<div class="row">
        <div class="col s12 m6">
          <div class="card #fff3e0 orange lighten-5">
            <div class="card-content black-text">
              <p>更新が完了しました</p>
            </div>
            <div class="card-action">
              <a href="/">投稿一覧へ戻る</a>
            </div>
          </div>
        </div>
      </div>

app/views/users/show.html.erb
<div class="contents row">
<p><%= @name %>さんの投稿一覧</p>

<% @tweets.each do |tweet| %>
<%= render partial: "./tweets/tweet", locals: {tweet: tweet} %>

<% end %>
<%= paginate(@tweets) %>

</div>